# Generated by Django 3.0.2 on 2020-01-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'login',
                'db_table': 'tbl_login',
            },
        ),
    ]
